name: respy-development
channels:
  - defaults
  - conda-forge
  - OpenSourceEconomics
dependencies:
  - python=3.7
  - pip
  - respy
  - click
  - codecov
  - conda-build
  - doc8
  - estimagic>=0.0.14
  - jupyterlab
  - matplotlib
  - mkl
  - nbsphinx=0.4.2
  - numba
  - numpydoc
  - pandas>=0.24
  - pyaml
  - pytest
  - pytest-cov
  - pytest-xdist
  - restructuredtext_lint
  - scipy
  - sphinx
  - sphinx-autobuild
  - tox-conda
  - seaborn
  - chaospy
  - pip:
    - apprise
    - pre-commit
